matrix:
  include:
    - language: node_js
      node_js:
        - node
      cache: npm

      script:
        - ./bin/run create --help
        - ./bin/run interactive --help
        - npm run test

    - language: objective-c
      before_install:
        - gem install xcov
        - gem update fastlane
      install:
        - npm install
      # Xcode version check https://docs.travis-ci.com/user/reference/osx/#xcode-version
      osx_image: xcode11
      script:
        - ./bin/run create ios my-app com.mycompany --ios_min_sdk=12.2 --ios_template=tabbar --internet_permission
        - chmod +x travis/script.sh
        - travis/script.sh
      after_success:
        - chmod +x travis/after_success_script.sh
        - travis/after_success_script.sh
