# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  dest "Run tests"
  lane :test do
    scan(
      scheme: "{{app_name}}",
      workspace: "{{app_name}}.xcodeproj",
      clean: true,
      code_coverage: true,
      skip_slack: true,
      sdk: "iphonesimulator",
      destination: "platform=iOS Simulator,OS=12.2,name=iPhone 6"
    )
  end

  desc "Test coverage"
  lane :report_test_coverage do
    xcov(
      scheme: "{{app_name}}",
      workspace: "{{app_name}}.xcodeproj",
      output_directory: "xcov_output"
    )
  end
end
